export const REACT_APP_TELEGRAM_API_ID = process.env.REACT_APP_TELEGRAM_API_ID
export const REACT_APP_TELEGRAM_API_HASH = process.env.REACT_APP_TELEGRAM_API_HASH
export const REACT_APP_TELEGRAM_STRING_SESSION = process.env.REACT_APP_TELEGRAM_STRING_SESSION
export const REACT_APP_TELEGRAM_SUPPORT_MEMBERS: string[] = process.env.REACT_APP_TELEGRAM_SUPPORT_MEMBER?.split(",") ?? []
